### ISSUE TITLE
Multi-level matching

### ISSUE THREAD

**Issue by jerry73204** [willcrichton/tyrade#3]
I'm working on type level list. The list can be represented by an enum-like type.

```rust
pub enum List {
    Nil,
    Cons(Type, List)
}
```

To obtain the last element of list, we recursively checks if the list has single element or more, and is assumed not to be empty. I tried two ways of writing.

The first is apparently invalid for now since tyrade cannot match on type.
```rust
pub fn Last(L: List) -> Type {
    match L {
        Cons(Head1 @ Type, Nil) => { // Nil is a type here
            Head1
        }
        Cons(Head1 @ Type, Cons(Head2 @ Type, Tail @ List) @ List) => {
            Last(Cons(Head2 @ Type, Tail @ List))
        }

    }
}
```

I tried two level matching. However, it complains about `Invalid match on Tail1` error.
```rust
pub fn Last(L: List) -> Type {
    match L {
        Cons(Head1 @ Type, Tail1 @ List) => {
            match Tail1 {
                Nil => Head1,
                Cons(Head2 @ Type, Tail2 @ List) => Last(Cons(Head2, Tail2))
            }
        }
    }
}
```

**Comment by willcrichton** [comment]
Hey @jerry73204, thanks for pointing this out. I see the issue -- right now, tyrade only supports matching on function arguments, not on variables defined within the function. (That's counter-intuitive, for sure!)

If you want to just get your task done, you can rewrite it like this:

```rust
  pub fn LastHelper(L: TList, T: Type) -> Type {
    match L {
      Nil => T,
      Cons(Head @ Type, L2 @ TList) => {
        LastHelper(L2, Head)
      }
    }
  }

  pub fn Last(L: TList) -> Type {
    LastHelper(L, ())
  }
```

In the meantime, I'll think about how to solve this issue.

**Comment by jerry73204** [comment]
Thanks! I looked into the [source code](https://github.com/willcrichton/tyrade/blob/548853803b744a459627ea795a5ae280c044b00a/tyrade-macro/src/trans.rs#L189-L215). Look like the recursive pattern matching is not ready yet.

**Comment by willcrichton** [comment]
Just added support for nested pattern matching in 51ec66874f9aad49f28bcce782c5396558cc5fbc. The following program now compiles correctly:

```rust
tyrade! {
  pub fn Last(L: TList) -> Type {
    match L {
      Nil => (),
      Cons(Head @ Type, Tail @ TList) => {
        match Tail {
          Nil => Head,
          Cons(Head2 @ Type, Tail2 @ TList) => Last(Tail)
        }
      }
    }
  }
}
```

**Comment by willcrichton** [comment]
Unfortunately, it doesn't seem easy to do `Cons(_, _)` right now. Since Rust doesn't support the syntax `Cons(_ @ Type, _ @ TList)`. But maybe we can figure out another way to do wildcards.
